repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check .
        language: system
        pass_filenames: false

      - id: ruff-format
        name: ruff format check
        entry: uv run ruff format --check .
        language: system
        pass_filenames: false

      - id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        pass_filenames: false
